"""Added relationships and cascade deletes

Revision ID: 0a7fbd405ae5
Revises: dcba2c8bddb5
Create Date: 2024-07-11 06:18:16.936507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7fbd405ae5'
down_revision = 'dcba2c8bddb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_constraint('fk_auctions_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_auctions_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_constraint('fk_bids_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_bids_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_comments_user_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_comments_user_id_users'), 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_comments_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_comments_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('bids', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_bids_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_bids_user_id_users', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('auctions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_auctions_user_id_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_auctions_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
